version: "3.7"

services:
  ai-jam:
    image: michaelnau/ai-jam:latest
    ports:
      - 5500:5500
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney 
      - URL=michael-naughton.com
      - SUBDOMAINS=www,
      - DNSPLUGIN=linode
      - VALIDATION=http
      - EMAIL=michael.naughton77@gmail.com
    volumes:
      - /root/mike/appdata/swag:/config
    ports:
      - 443:443
    restart: unless-stopped
